#!/bin/tcsh -f


foreach x (*.tex)
echo $x
sed -e 's/{Gazdar81}/{Gazdar81a}/g'   $x >$x.neu
end


#foreach x (*.tex)
#echo $x
#sed -e 's/subind}{Scrambling/subind}{Scrambling@\{\\it Scrambling\\\/\}/g' $x >$x.neu
#end

foreach x (*.tex)
printf "."
mv -f $x $x.old
mv $x.neu $x
end

printf "\n"

